### ISSUE TITLE
intersection doesn't look at all arrays

### ISSUE THREAD

**Issue by coleman07** [FrontendMasters/fm-snippets#1]
intersection will not look at last array because you substract 1 from length of arguments. If you had 4 arrays which would be similar to removing the -1 on arguments, the solution produces a result with numbers not
in second array

**Comment by laniehei** [comment]
Could you be more specific as to which problem in which course you are referring to?

**Comment by 1Marc** [comment]
Closing for lack of details.

**Comment by coleman07** [comment]
I didn't write the comment in the right spot - can I redo after I look at
my answer one more time?

Sean Coleman
