### ISSUE TITLE
Why should we define step

### ISSUE THREAD

**Issue by nassif7** [FrontendMasters/fm-snippets#21]
https://github.com/FrontendMasters/fm-snippets/blame/60b530b794cad7ffd435effc0c988f99531226a1/javascript-hard-parts-v2/closures.js#L54

do we need to define step here? 
wouldn't be sufficient to have the function like this 
```
function addByX(x) {
	function addBy(input) {
    return input + x
  }
  return addBy
}
```

**Comment by dtauer** [comment]
You are correct. The only reason step is in there is because it was in the original challenge problem.
