### ISSUE TITLE
Issue in Challenge 4 in callbacks.js

### ISSUE THREAD

**Issue by Azzarox** [FrontendMasters/fm-snippets#23]
The description of the challenge states that the function must not return anything. 

Challenge 4 decription:
> Create a function called forEach that takes an array and a callback, and runs the callback on each element of the array. forEach does not return anything. 

However the solution clearly has a return keyword. 
Challenge 4 solution:
```
function forEach(array, callback) {
	let arr = []
  for(let i=0; i<array.length; i++) {
    arr.push(callback(array[i]))
  }
	return arr
}
```

Also for challenge 5, the definition states that I should use the forEach however without forEach returning the challenge is not possible.

Challenge 5 decription:

> In challenge 3, you've created a function called map. In this challenge, you're going to rebuild the map function by creating a function called mapWith. This time you're going to use forEach inside of mapWith instead of using a for loop. 

I don't know whether the challenges description are wrong or the provided solution but there is a mismatch.

**Comment by dtauer** [comment]
Thanks for catching this. Just fixed the solution

**Comment by karinchechik** [comment]
Hey @dtauer,

I would like to suggest another modification to this solution.
Since the `return` statement was removed, the new array has no use. So you can also remove the array creation and the `push` part.
This function works without using the new array.

This was my solution for challenge 4:

```
function forEach(array, callback) {
    for (let i = 0; i < array.length; i++) {
        callback(array[i]);
    }
}
```

Hope it helps 😊
