### ISSUE TITLE
Missing part of assignment.

### ISSUE THREAD

**Issue by jakub-golan** [FrontendMasters/fm-snippets#4]
https://github.com/FrontendMasters/fm-snippets/blob/0286522fd6f5aa0fa192759976b126f0ed3718d9/2018-01-22-javascript-hard-parts/fem-JavaScriptTheHardParts-ClosuresSolutions.js#L106

Hi, in the solution you are missing part of the assignment that says to pass any arguments after wait to the callback function.

**Comment by sonicfive** [comment]
On line 51, the correct assignment should be:
`total += callback(array[i],initialValue) `
If you only use = you will only keep the last element in the array and not the sum of the elements of the array
